# Generated by Django 5.2.4 on 2025-09-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telefone',
        ),
        migrations.AddField(
            model_name='user',
            name='curso',
            field=models.CharField(blank=True, choices=[('administracao', 'Administração'), ('agricultura', 'Agricultura'), ('agroecologia', 'Agroecologia'), ('agropecuaria', 'Agropecuária'), ('alimentos', 'Alimentos'), ('apicultura', 'Apicultura'), ('biocombustiveis', 'Biocombustíveis'), ('comercio', 'Comércio'), ('controle_ambiental', 'Controle Ambiental'), ('edificacoes', 'Edificações'), ('eletromecanica', 'Eletromecânica'), ('eletronica', 'Eletrônica'), ('eletrotecnica', 'Eletrotécnica'), ('equipamentos_biomedicos', 'Equipamentos Biomédicos'), ('eventos', 'Eventos'), ('geologia', 'Geologia'), ('informatica', 'Informática'), ('informatica_internet', 'Informática para Internet'), ('jogos_digitais', 'Jogos Digitais'), ('lazer', 'Lazer'), ('logistica', 'Logística'), ('manutencao_informatica', 'Manutenção e Suporte em Informática'), ('mecanica', 'Mecânica'), ('mecatronica', 'Mecatrônica'), ('meio_ambiente', 'Meio Ambiente'), ('mineracao', 'Mineração'), ('multimidia', 'Multimídia'), ('quimica', 'Química'), ('recursos_pesqueiros', 'Recursos Pesqueiros'), ('refrigeracao_climatizacao', 'Refrigeração e Climatização'), ('textil', 'Têxtil'), ('vestuario', 'Vestuário'), ('zootecnia', 'Zootecnia')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='users/foto_perfil/'),
        ),
        migrations.AddField(
            model_name='user',
            name='genero',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='idade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tipo_escola',
            field=models.CharField(blank=True, choices=[('administracao', 'Particular'), ('agricultura', 'Pública'), ('outra', 'Outra')], max_length=15, null=True),
        ),
    ]
