# Generated by Django 5.2.4 on 2025-09-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_avatar_remove_user_telefone_user_curso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='foto_perfil',
        ),
        migrations.RemoveField(
            model_name='user',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='user',
            name='idade',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatar/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_escola',
            field=models.CharField(blank=True, choices=[('particular', 'Particular'), ('pública', 'Pública'), ('outra', 'Outra')], max_length=15, null=True),
        ),
    ]
