# Generated by Django 5.2.4 on 2025-10-05 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_foto_perfil_remove_user_genero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tipo_escola',
        ),
    ]
