# Generated by Django 5.2.4 on 2025-10-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_card_image_alter_member_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Sobre'},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Sobre'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Membro'},
        ),
        migrations.AlterField(
            model_name='about',
            name='subtitle',
            field=models.CharField(max_length=200, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='about',
            name='text',
            field=models.TextField(verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(upload_to='cards_images/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(upload_to='members_images/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='member',
            name='occupation',
            field=models.CharField(max_length=200, verbose_name='Ocupação'),
        ),
    ]
