# Generated by Django 5.2.4 on 2025-10-30 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_card_imagem_card_icone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
