# Generated by Django 5.2.4 on 2025-10-05 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_about_options_alter_card_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={},
        ),
    ]
