# Generated by Django 5.2.8 on 2025-11-25 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('instituicao', models.CharField(max_length=10, verbose_name='Instituição')),
            ],
            options={
                'ordering': ['ano'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Simulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('subtitulo', models.CharField(max_length=50, verbose_name='Subtítulo')),
            ],
            options={
                'ordering': ['ano'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gabarita_if.disciplina')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens-das-questoes/')),
                ('gabarito_comentado', models.TextField()),
                ('video_solucao', models.URLField(blank=True, max_length=500, null=True, verbose_name='Vídeo solução')),
                ('alternativa_a', models.CharField(max_length=500, verbose_name='Alternativa A')),
                ('alternativa_b', models.CharField(max_length=500, verbose_name='Alternativa B')),
                ('alternativa_c', models.CharField(max_length=500, verbose_name='Alternativa C')),
                ('alternativa_d', models.CharField(max_length=500, verbose_name='Alternativa D')),
                ('alternativa_correta', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gabarita_if.assunto')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gabarita_if.disciplina')),
                ('prova', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gabarita_if.prova')),
                ('simulados', models.ManyToManyField(blank=True, to='gabarita_if.simulado')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
            },
        ),
        migrations.CreateModel(
            name='ListaPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cor', models.CharField(default='#4cc49e', max_length=7)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('questoes', models.ManyToManyField(to='gabarita_if.questao', verbose_name='Questões')),
            ],
            options={
                'verbose_name_plural': 'Listas Personalizadas',
            },
        ),
        migrations.CreateModel(
            name='RespostaQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativa_escolhida', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('acertou', models.BooleanField()),
                ('prova', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gabarita_if.prova')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gabarita_if.questao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('simulado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gabarita_if.simulado')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalizada', models.BooleanField()),
                ('prova', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gabarita_if.prova')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('simulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gabarita_if.simulado')),
            ],
        ),
        migrations.CreateModel(
            name='TextoDeApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('texto', models.TextField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='textos-de-apoio/')),
                ('prova', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gabarita_if.prova')),
                ('questoes', models.ManyToManyField(blank=True, to='gabarita_if.questao', verbose_name='Questões')),
                ('simulados', models.ManyToManyField(blank=True, to='gabarita_if.simulado')),
            ],
            options={
                'verbose_name': 'Texto de Apoio',
                'verbose_name_plural': 'Textos de Apoio',
            },
        ),
    ]
