# Generated by Django 5.2.8 on 2025-12-05 12:20

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gabarita_if.disciplina')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', tinymce.models.HTMLField()),
                ('gabarito_comentado', tinymce.models.HTMLField()),
                ('video_solucao', models.URLField(blank=True, max_length=500, null=True, verbose_name='Vídeo solução')),
                ('alternativa_a', models.CharField(max_length=500, verbose_name='Alternativa A')),
                ('alternativa_b', models.CharField(max_length=500, verbose_name='Alternativa B')),
                ('alternativa_c', models.CharField(max_length=500, verbose_name='Alternativa C')),
                ('alternativa_d', models.CharField(max_length=500, verbose_name='Alternativa D')),
                ('alternativa_correta', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gabarita_if.assunto')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gabarita_if.disciplina')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
            },
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('ano', models.PositiveIntegerField()),
                ('instituicao', models.CharField(blank=True, max_length=10, null=True, verbose_name='Instituição')),
                ('questoes', models.ManyToManyField(to='gabarita_if.questao', verbose_name='Questões')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Caderno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cor', models.CharField(default='#4cc49e', max_length=7)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('questoes', models.ManyToManyField(to='gabarita_if.questao', verbose_name='Questões')),
            ],
        ),
        migrations.CreateModel(
            name='Simulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('ano', models.PositiveIntegerField()),
                ('subtitulo', models.CharField(max_length=50, verbose_name='Subtítulo')),
                ('questoes', models.ManyToManyField(to='gabarita_if.questao', verbose_name='Questões')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TentativaAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalizada', models.BooleanField()),
                ('prova', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gabarita_if.prova')),
                ('simulado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gabarita_if.simulado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tentativa da Avaliação',
                'verbose_name_plural': 'Tentativas das Avaliações',
            },
        ),
        migrations.CreateModel(
            name='RespostaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativa_escolhida', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('acertou', models.BooleanField()),
                ('respondida_em', models.DateTimeField(auto_now_add=True)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='gabarita_if.questao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tentativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gabarita_if.tentativaavaliacao')),
            ],
            options={
                'verbose_name': 'Resposta do Usuário',
                'verbose_name_plural': 'Respostas dos Usuários',
            },
        ),
        migrations.CreateModel(
            name='TextoApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('texto', tinymce.models.HTMLField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='textos-de-apoio/')),
                ('questoes', models.ManyToManyField(to='gabarita_if.questao', verbose_name='Questões')),
            ],
            options={
                'verbose_name': 'Texto de Apoio',
                'verbose_name_plural': 'Textos de Apoio',
            },
        ),
    ]
