# Generated by Django 5.2.4 on 2025-10-02 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('simulado', 'Simulado'), ('prova', 'Prova')], max_length=10)),
                ('year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PORTUGUES', 'Português'), ('MATEMATICA', 'Matemática')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_solution', models.TextField()),
                ('video_solution', models.FileField(blank=True, upload_to='lists_pdfs/')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gabarita_if.assessment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gabarita_if.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='supporting_images/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gabarita_if.question')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gabarita_if.question')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('TIPOLOGIA_GENEROS', 'Tipologia e Gêneros Textuais'), ('INTERPRETACAO_TEXTO', 'Interpretação de Texto'), ('VARIACAO_LINGUISTICA', 'Variação Linguística'), ('FONETICA', 'Fonética'), ('ACENTUACAO_PONTUACAO', 'Acentuação Gráfica e Pontuação'), ('CRASE', 'Crase'), ('ESTRUTURA_PALAVRAS', 'Estrutura e Formação das Palavras'), ('FUNCOES_LINGUAGEM', 'Funções da Linguagem'), ('SEMANTICA', 'Semântica'), ('CLASSES_PALAVRAS', 'Classes de Palavras'), ('CONCORDANCIA', 'Concordância Nominal e Verbal'), ('REGENCIA', 'Regência Nominal e Verbal'), ('TIPOS_VERBOS', 'Tipos de Verbos'), ('FUNCOES_SINTATICAS', 'Funções Sintáticas'), ('PERIODO_COMPOSTO', 'Período Composto'), ('USO_QUE_E_SE', 'Uso do Que e Se'), ('SISTEMA_NUMERACAO', 'Sistema de Numeração'), ('CONJUNTOS_NUMERICOS', 'Conjuntos Numéricos'), ('OPERACOES_FUNDAMENTAIS', 'Operações Fundamentais'), ('MULTIPLOS_DIVISORES', 'Múltiplos e Divisores'), ('MMC_MDC', 'MMC e MDC'), ('FRACOES_DECIMAIS', 'Frações e Números Decimais'), ('EXPRESSOES_ALGEBRICAS', 'Expressões Algébricas'), ('UNIDADES_MEDIDA', 'Unidades de Medida'), ('NOTACAO_CIENTIFICA', 'Notação Científica'), ('POTENCIACAO_RADICACAO', 'Potenciação e Radiciação'), ('RAZAO_PROPORCAO', 'Razão e Proporção'), ('REGRA_DE_TRES', 'Regra de Três'), ('PORCENTAGEM', 'Porcentagem'), ('GRAFICOS_PAR_ORDENADO', 'Gráficos/Par Ordenado'), ('MEDIA_SIMPLES_PONDERADA', 'Média Simples e Ponderada'), ('ANGULOS_TRIANGULOS', 'Ângulos e Triângulos'), ('TEOREMA_TALES', 'Teorema de Tales'), ('TEOREMA_PITAGORAS', 'Teorema de Pitágoras'), ('QUADRILATEROS', 'Quadriláteros'), ('CIRCULO_CIRCUNFERENCIA', 'Círculo e Circunferência'), ('VOLUME_SOLIDOS', 'Volume de Sólidos'), ('PROBABILIDADE', 'Probabilidade'), ('MEDIDAS_TEMPO', 'Medidas de Tempo'), ('EQUACAO_1_2_GRAU', 'Equação do 1º e 2º Grau'), ('SISTEMA_EQUACOES', 'Sistema de Equações'), ('JUROS_SIMPLES', 'Juros Simples'), ('PRODUTOS_NOTAVEIS', 'Produtos Notáveis'), ('CONSUMO_ENERGIA_ELETRICA', 'Consumo de Energia Elétrica')], max_length=50)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gabarita_if.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gabarita_if.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gabarita_if.topic')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gabarita_if.topic'),
        ),
        migrations.CreateModel(
            name='PDFList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='lists_pdfs/')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gabarita_if.subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gabarita_if.topic')),
            ],
        ),
    ]
