# Generated by Django 5.2.8 on 2025-11-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='alternativa_a',
            field=models.CharField(max_length=500, verbose_name='Alternativa A'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='alternativa_b',
            field=models.CharField(max_length=500, verbose_name='Alternativa B'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='alternativa_c',
            field=models.CharField(max_length=500, verbose_name='Alternativa C'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='alternativa_d',
            field=models.CharField(max_length=500, verbose_name='Alternativa D'),
        ),
    ]
