# Generated by Django 5.2.8 on 2025-12-29 22:31

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=tinymce.models.HTMLField(),
        ),
    ]
