# Generated by Django 5.2.4 on 2025-10-09 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gabarita_if', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assunto',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gabarita_if.disciplina'),
        ),
        migrations.AddField(
            model_name='filtro',
            name='assunto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gabarita_if.assunto'),
        ),
        migrations.AddField(
            model_name='filtro',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gabarita_if.disciplina'),
        ),
        migrations.AddField(
            model_name='filtro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questao',
            name='assunto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gabarita_if.assunto'),
        ),
        migrations.AddField(
            model_name='questao',
            name='avaliacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gabarita_if.avaliacao', verbose_name='Avaliação'),
        ),
        migrations.AddField(
            model_name='questao',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gabarita_if.disciplina'),
        ),
        migrations.AddField(
            model_name='alternativa',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gabarita_if.questao'),
        ),
        migrations.AddField(
            model_name='textoapoio',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gabarita_if.questao'),
        ),
    ]
