# Generated by Django 5.2.4 on 2025-11-12 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listapdf',
            name='assunto',
        ),
        migrations.RemoveConstraint(
            model_name='questao',
            name='questao_must_have_prova_or_simulado',
        ),
        migrations.DeleteModel(
            name='ListaPDF',
        ),
    ]
