# Generated by Django 5.2.4 on 2025-11-15 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gabarita_if', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assunto',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gabarita_if.disciplina'),
        ),
        migrations.AddField(
            model_name='listapersonalizada',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questao',
            name='assunto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gabarita_if.assunto'),
        ),
        migrations.AddField(
            model_name='questao',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gabarita_if.disciplina'),
        ),
        migrations.AddField(
            model_name='questao',
            name='prova',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET, to='gabarita_if.prova'),
        ),
        migrations.AddField(
            model_name='listapersonalizada',
            name='questao',
            field=models.ManyToManyField(blank=True, to='gabarita_if.questao', verbose_name='Questões'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gabarita_if.questao'),
        ),
        migrations.AddField(
            model_name='questao',
            name='simulado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET, to='gabarita_if.simulado'),
        ),
        migrations.AddField(
            model_name='questao',
            name='texto_de_apoio',
            field=models.ManyToManyField(blank=True, to='gabarita_if.textodeapoio', verbose_name='Textos de apoio'),
        ),
        migrations.AddConstraint(
            model_name='questao',
            constraint=models.UniqueConstraint(condition=models.Q(('prova__isnull', False), ('simulado__isnull', False)), fields=('prova', 'simulado'), name='prova_or_simulado_not_both'),
        ),
    ]
