# Generated by Django 5.2.4 on 2025-10-08 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'verbose_name': 'Comentário'},
        ),
        migrations.AlterModelOptions(
            name='listapersonalizada',
            options={'verbose_name_plural': 'Listas Personalizadas'},
        ),
        migrations.AlterModelOptions(
            name='questao',
            options={'verbose_name': 'Questão', 'verbose_name_plural': 'Questões'},
        ),
        migrations.AlterModelOptions(
            name='textoapoio',
            options={'verbose_name': 'Texto de Apoio', 'verbose_name_plural': 'Textos de Apoio'},
        ),
    ]
