# Generated by Django 5.2.8 on 2025-11-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questao',
            old_name='simulado',
            new_name='simulados',
        ),
        migrations.AlterField(
            model_name='textodeapoio',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
    ]
