# Generated by Django 5.2.4 on 2025-10-31 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtro',
            name='assunto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET, to='gabarita_if.assunto'),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET, to='gabarita_if.disciplina'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='prova',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET, to='gabarita_if.prova'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='simulado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET, to='gabarita_if.simulado'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='texto_de_apoio',
            field=models.ManyToManyField(blank=True, null=True, to='gabarita_if.textodeapoio', verbose_name='Texto de Apoio'),
        ),
    ]
