# Generated by Django 5.2.4 on 2025-10-17 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alternativa',
            old_name='alternativa_correta',
            new_name='correta',
        ),
    ]
