# Generated by Django 5.2.4 on 2025-10-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='correta',
            field=models.BooleanField(unique=True, verbose_name='Esta é a alternativa correta?'),
        ),
    ]
