# Generated by Django 5.2.8 on 2026-09-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='blocos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='questao',
            name='ano',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Ano'),
        ),
    ]
