# Generated by Django 5.2.8 on 2025-11-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova',
            name='questoes',
            field=models.ManyToManyField(to='gabarita_if.questao', verbose_name='Questões'),
        ),
        migrations.AlterField(
            model_name='simulado',
            name='questoes',
            field=models.ManyToManyField(to='gabarita_if.questao', verbose_name='Questões'),
        ),
    ]
