# Generated by Django 5.2.4 on 2025-11-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listapdf',
            name='nome',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
