# Generated by Django 5.2.8 on 2025-12-04 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='imagem',
        ),
    ]
