# Generated by Django 5.2.8 on 2025-12-23 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respostaavaliacao',
            options={'verbose_name': 'Resposta da Avaliação', 'verbose_name_plural': 'Respostas das Avaliações'},
        ),
        migrations.AlterModelOptions(
            name='respostaquestao',
            options={'verbose_name': 'Resposta da Questão', 'verbose_name_plural': 'Respostas das Questões'},
        ),
    ]
