# Generated by Django 5.2.4 on 2025-10-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0002_alter_filtro_assunto_alter_filtro_disciplina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='video_solucao',
            field=models.FileField(blank=True, null=True, upload_to='videos-solucao/', verbose_name='Vídeo Solução'),
        ),
    ]
