# Generated by Django 5.2.4 on 2025-10-03 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0002_alter_topic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='name',
        ),
    ]
