# Generated by Django 5.2.8 on 2025-11-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0002_alter_prova_questoes_alter_simulado_questoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='fonte',
        ),
        migrations.AlterField(
            model_name='prova',
            name='instituicao',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Instituição'),
        ),
        migrations.DeleteModel(
            name='Fonte',
        ),
    ]
