# Generated by Django 5.2.8 on 2026-09-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0002_avaliacao_blocos_questao_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='ano',
            field=models.PositiveIntegerField(default=2024, verbose_name='Ano'),
            preserve_default=False,
        ),
    ]
