# Generated by Django 5.2.8 on 2025-11-22 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0002_alter_questao_alternativa_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='prova',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gabarita_if.prova'),
        ),
        migrations.AlterField(
            model_name='textodeapoio',
            name='prova',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gabarita_if.prova'),
        ),
    ]
