# Generated by Django 5.2.8 on 2025-11-25 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0002_remove_respostaquestao_prova'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respostaavaliacao',
            name='prova',
        ),
    ]
