# Generated by Django 5.2.8 on 2026-08-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0002_alter_comentario_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='ano',
            field=models.PositiveIntegerField(default=2024, verbose_name='Ano'),
            preserve_default=False,
        ),
    ]
