# Generated by Django 5.2.4 on 2025-10-20 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0002_alter_alternativa_correta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='texto_de_apoio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET, to='gabarita_if.textodeapoio'),
        ),
    ]
