# Generated by Django 5.2.4 on 2025-11-05 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0002_listapdf_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listapdf',
            name='nome',
        ),
    ]
