# Generated by Django 5.2.4 on 2025-10-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0003_remove_topic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='name',
            field=models.CharField(choices=[('TIPOLOGIA_GENEROS', 'Tipologia e Gêneros Textuais'), ('INTERPRETACAO_TEXTO', 'Interpretação de Texto'), ('VARIACAO_LINGUISTICA', 'Variação Linguística'), ('FONETICA', 'Fonética'), ('ACENTUACAO_PONTUACAO', 'Acentuação Gráfica e Pontuação'), ('CRASE', 'Crase'), ('ESTRUTURA_PALAVRAS', 'Estrutura e Formação das Palavras'), ('FUNCOES_LINGUAGEM', 'Funções da Linguagem'), ('SEMANTICA', 'Semântica'), ('CLASSES_PALAVRAS', 'Classes de Palavras'), ('CONCORDANCIA', 'Concordância Nominal e Verbal'), ('REGENCIA', 'Regência Nominal e Verbal'), ('TIPOS_VERBOS', 'Tipos de Verbos'), ('FUNCOES_SINTATICAS', 'Funções Sintáticas'), ('PERIODO_COMPOSTO', 'Período Composto'), ('USO_QUE_E_SE', 'Uso do Que e Se'), ('SISTEMA_NUMERACAO', 'Sistema de Numeração'), ('CONJUNTOS_NUMERICOS', 'Conjuntos Numéricos'), ('OPERACOES_FUNDAMENTAIS', 'Operações Fundamentais'), ('MULTIPLOS_DIVISORES', 'Múltiplos e Divisores'), ('MMC_MDC', 'MMC e MDC'), ('FRACOES_DECIMAIS', 'Frações e Números Decimais'), ('EXPRESSOES_ALGEBRICAS', 'Expressões Algébricas'), ('UNIDADES_MEDIDA', 'Unidades de Medida'), ('NOTACAO_CIENTIFICA', 'Notação Científica'), ('POTENCIACAO_RADICACAO', 'Potenciação e Radiciação'), ('RAZAO_PROPORCAO', 'Razão e Proporção'), ('REGRA_DE_TRES', 'Regra de Três'), ('PORCENTAGEM', 'Porcentagem'), ('GRAFICOS_PAR_ORDENADO', 'Gráficos/Par Ordenado'), ('MEDIA_SIMPLES_PONDERADA', 'Média Simples e Ponderada'), ('ANGULOS_TRIANGULOS', 'Ângulos e Triângulos'), ('TEOREMA_TALES', 'Teorema de Tales'), ('TEOREMA_PITAGORAS', 'Teorema de Pitágoras'), ('QUADRILATEROS', 'Quadriláteros'), ('CIRCULO_CIRCUNFERENCIA', 'Círculo e Circunferência'), ('VOLUME_SOLIDOS', 'Volume de Sólidos'), ('PROBABILIDADE', 'Probabilidade'), ('MEDIDAS_TEMPO', 'Medidas de Tempo'), ('EQUACAO_1_2_GRAU', 'Equação do 1º e 2º Grau'), ('SISTEMA_EQUACOES', 'Sistema de Equações'), ('JUROS_SIMPLES', 'Juros Simples'), ('PRODUTOS_NOTAVEIS', 'Produtos Notáveis'), ('CONSUMO_ENERGIA_ELETRICA', 'Consumo de Energia Elétrica')], default='', max_length=50),
        ),
    ]
