# Generated by Django 5.2.4 on 2025-11-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0003_remove_listapdf_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listapdf',
            options={'verbose_name': 'Lista PDF', 'verbose_name_plural': 'Listas PDF'},
        ),
        migrations.AddField(
            model_name='listapdf',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
