# Generated by Django 5.2.4 on 2025-10-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0003_alter_questao_texto_de_apoio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='correta',
            field=models.BooleanField(verbose_name='Esta é a alternativa correta?'),
        ),
    ]
