# Generated by Django 5.2.4 on 2025-10-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0003_alter_questao_video_solucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='texto_de_apoio',
            field=models.ManyToManyField(blank=True, default='----', null=True, to='gabarita_if.textodeapoio', verbose_name='Texto de Apoio'),
        ),
    ]
