# Generated by Django 5.2.8 on 2026-08-21 20:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0003_questao_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='caderno',
            name='ano',
            field=models.PositiveIntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='caderno',
            name='assunto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gabarita_if.assunto'),
        ),
        migrations.AddField(
            model_name='caderno',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='caderno',
            name='disciplina',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gabarita_if.disciplina'),
        ),
        migrations.AlterField(
            model_name='caderno',
            name='cor',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
