# Generated by Django 5.2.4 on 2025-10-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0003_alter_alternativa_correta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='correta',
            field=models.BooleanField(default=False, verbose_name='Esta é a alternativa correta?'),
        ),
    ]
