# Generated by Django 5.2.8 on 2025-11-26 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0003_remove_questao_fonte_alter_prova_instituicao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prova',
            options={},
        ),
        migrations.AlterModelOptions(
            name='simulado',
            options={},
        ),
    ]
