# Generated by Django 5.2.4 on 2025-10-18 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0004_alter_alternativa_correta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='modelo',
            new_name='tipo',
        ),
    ]
