# Generated by Django 5.2.4 on 2025-11-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0004_alter_listapdf_options_listapdf_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='assunto',
            name='pdf_lista',
            field=models.FileField(blank=True, null=True, upload_to='listas-pdf/', verbose_name='Lista PDF deste assunto'),
        ),
        migrations.DeleteModel(
            name='ListaPDF',
        ),
    ]
