# Generated by Django 5.2.8 on 2025-11-26 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0004_alter_prova_options_alter_simulado_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textoapoio',
            name='prova',
        ),
        migrations.RemoveField(
            model_name='textoapoio',
            name='simulados',
        ),
    ]
