# Generated by Django 5.2.8 on 2026-08-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0004_caderno_ano_caderno_assunto_caderno_criado_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='ano',
        ),
    ]
