# Generated by Django 5.2.4 on 2025-10-05 21:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0005_alter_comment_created_at_alter_customlist_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavedFilter',
            new_name='Filter',
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(choices=[('TIPOLOGIA_GENEROS', 'Tipologia e Gêneros Textuais'), ('SISTEMA_NUMERACAO', 'Sistema de Numeração')], default='', max_length=50),
        ),
    ]
