# Generated by Django 5.2.8 on 2025-11-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0005_remove_textoapoio_prova_remove_textoapoio_simulados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textoapoio',
            name='questoes',
            field=models.ManyToManyField(to='gabarita_if.questao', verbose_name='Questões'),
        ),
    ]
