# Generated by Django 5.2.4 on 2025-10-21 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0005_alter_questao_prova_alter_questao_simulado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='prova',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET, to='gabarita_if.prova'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='simulado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET, to='gabarita_if.simulado'),
        ),
    ]
