# Generated by Django 5.2.8 on 2026-08-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0005_remove_questao_ano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caderno',
            name='ano',
        ),
    ]
