# Generated by Django 5.2.4 on 2025-10-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0005_alter_questao_texto_de_apoio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='texto_de_apoio',
            field=models.ManyToManyField(blank=True, to='gabarita_if.textodeapoio', verbose_name='Texto de Apoio'),
        ),
    ]
