# Generated by Django 5.2.4 on 2025-10-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0005_rename_modelo_avaliacao_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assunto',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
