# Generated by Django 5.2.4 on 2025-11-05 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0005_assunto_pdf_lista_delete_listapdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assunto',
            name='pdf_lista',
        ),
        migrations.CreateModel(
            name='ListaPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='listas-pdf/', verbose_name='PDF')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gabarita_if.assunto')),
            ],
            options={
                'verbose_name': 'Lista PDF',
                'verbose_name_plural': 'Listas PDF',
            },
        ),
    ]
