# Generated by Django 5.2.8 on 2026-09-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0006_remove_caderno_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='caderno',
            name='ano',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
