# Generated by Django 5.2.4 on 2025-10-22 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0006_alter_questao_prova_alter_questao_simulado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listapersonalizada',
            old_name='criado_em',
            new_name='criada_em',
        ),
        migrations.CreateModel(
            name='ListaPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='listas-pdf/')),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gabarita_if.assunto')),
            ],
        ),
    ]
