# Generated by Django 5.2.4 on 2025-10-22 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0007_rename_criado_em_listapersonalizada_criada_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filtro',
            name='usuario',
        ),
    ]
