# Generated by Django 5.2.8 on 2026-09-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0008_merge_0007_caderno_ano_0007_repair_caderno_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caderno',
            name='ano',
        ),
        migrations.AlterField(
            model_name='caderno',
            name='cor',
            field=models.CharField(default='#4cc49e', max_length=7),
        ),
    ]
