# Generated by Django 5.2.4 on 2025-10-22 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0008_remove_filtro_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textodeapoio',
            old_name='nome',
            new_name='titulo',
        ),
    ]
