# Generated by Django 5.2.4 on 2025-10-23 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0009_rename_nome_textodeapoio_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='gabarito_comentado',
            field=models.TextField(verbose_name='Gabarito Comentado'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='texto_de_apoio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET, to='gabarita_if.textodeapoio', verbose_name='Texto de Apoio'),
        ),
        migrations.AlterField(
            model_name='textodeapoio',
            name='titulo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Título'),
        ),
    ]
