# Generated by Django 5.2.4 on 2025-10-25 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0010_alter_questao_gabarito_comentado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questao',
            old_name='texto',
            new_name='enunciado',
        ),
    ]
