# Generated by Django 5.2.4 on 2025-10-28 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0011_rename_texto_questao_enunciado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listapersonalizada',
            name='criada_em',
        ),
    ]
