# Generated by Django 5.2.4 on 2025-10-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0012_remove_listapersonalizada_criada_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='listapersonalizada',
            name='cor',
            field=models.CharField(default='#4cc49e', help_text='Escolha uma cor', max_length=7),
        ),
    ]
