# Generated by Django 5.2.4 on 2025-10-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabarita_if', '0013_listapersonalizada_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listapersonalizada',
            name='cor',
            field=models.CharField(default='#4cc49e', max_length=7),
        ),
    ]
