# Generated by Django 5.2.8 on 2025-11-20 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='curso',
        ),
    ]
